# Server Port
server.port=8080

# OpenRouteService API Key (Unga actual API key-ah replace pannunga)
OpenRouteService.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6Ijg3NjhhYTlhNDVmODQ4NTM5OTY5YjQyMjRlODIyMTg2IiwiaCI6Im11cm11cjY0In0=

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/saferoute_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=2228

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Suppress Open-In-View Warning in Logs
spring.jpa.open-in-view=false